ViewTitle: "&l[相思梦泽] - 鉴定"
Item:
  Name: "§7§l梦泽界限"
  Mats: WHITE_STAINED_GLASS_PANE
  Lore:
    - ""
    - "§7§l无法逾越的底线"
    - "§7§l§m================="
    - "§8§l§o维护团队：相思梦泽 - 冰爷"
VaultButton:
  Name: "&3&l[ 普通 ] 鉴定"
  Mats:
  Lore:
    - ""
    - "&7&l使用金币进行一次鉴定"
    - "&7&l可以解锁一个未鉴定的槽位"
    - "§7§l§m================="
    - "§8§l§o维护团队：相思梦泽 - 冰爷"
  Consume: 300
PointsButton:
  Name: "&3&l[ 高级 ] 鉴定"
  Mats:
  Lore:
    - ""
    - "&7&l使用点券进行一次鉴定"
    - "&7&l可以解锁一个未鉴定的槽位"
    - "§7§l§m================="
    - "§8§l§o维护团队：相思梦泽 - 冰爷"
  Consume: 50
# 配置文件版本，如果不熟悉这个是干啥的请不要修改。
Version: ${project.version}
# 自动更新配置文件
# [true - 开启 / false - 关闭]
AutoUpDate: true
# 调试开关，打开后可以看到详细的执行时间以及更多的执行日志
# [true - 开启 / false - 关闭]
Debug: false