name: RandomEntry
version: ${project.version}
main: vip.bingzi.randomentry.RandomEntry
depend: [Vault, PlayerPoints]
softdepend: [PlaceholderAPI, BZCore, Vault, PlayerPoints]
authors: [BingZi]
description: "冰系下的随机词条，类似鉴定的功能。"
commands:
  RandomEntry:
    aliases:
      - jd
      - bzjd
      - re
    permission: RandomEntry.use
permissions:
  RandomEntry.use:
    default: true
  RandomEntry.op:
    default: op
